name: Deploy Netlify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Deploy to Netlify
        uses: netlify/actions/cli@3185065f4ab2f6df6f2ef41ee013626e1c02a426
        with:
          args: deploy --prod --dir=. --site=warungnzals
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
